#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_TLSC6X)  += tlsc6x.o
tlsc6x-objs := tlsc6x_main.o
tlsc6x-objs += tlsc6x_comp.o

