#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2019 Fuzhou Rockchip Electronics Co., Ltd.

set -e

usage() {
	cat >&2 << USAGE
usage: $0 [-h] --dtb DTB

optional arguments:
  -h, --help            show this help message and exit
  --dtb DTB             the dtb file name
USAGE
}

# Parse command-line arguments
while [ $# -gt 0 ]; do
	case $1 in
		--dtb)
			DTB=$2
			shift 2
			;;
		-h)
			usage
			exit 0
			;;
		--help)
			usage
			exit 0
			;;
		*)
			shift
			;;
        esac
done

ITB=${BOOT_IMG}
ITS=boot.its
MKIMAGE="./rkbin/tools/mkimage"
MKIMAGE_ARG="-E -p 0x800"

check_mkimage()
{
	MKIMAGE=$(type -path ${MKIMAGE})
	if [ -z "${MKIMAGE}" ]; then
		# Doesn't exist
		echo '"mkimage" command not found - U-Boot images will not be built' >&2
		exit 1;
	fi
}

if [ -x ${srctree}/scripts/bmpconvert ]; then
	if [ -f boot.bmp ]; then
		${srctree}/scripts/bmpconvert boot.bmp;
	fi
	if [ -f logo_kernel.bmp ]; then
		${srctree}/scripts/bmpconvert logo_kernel.bmp;
	fi
	if [ -f logo_fastboot.bmp ]; then
		${srctree}/scripts/bmpconvert logo_fastboot.bmp;
	fi
fi


make ARCH=arm dtbs
python scripts/mkmultidtb.py ${DTB}

check_mkimage
${MKIMAGE} ${MKIMAGE_ARG} -f ${ITS} boot.img >/dev/null && \
echo "  Image:  boot.img is ready";

